future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: CIGMA-OE
url: https://cigma-oe.github.io/
name: CIGMA-OE
description: Comite interno de ingeniería matematica
facebook: cigmaoe
calendar: https://agregar-el-calendario-aqui
mailinglist: mailto:cigmaoe@gmail.com
gravatar_url:
disqus_username:
