future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: CIGMA-OE
url: https://cigma-oe.github.io/
name: CIGMA-OE
description: Comite interno de ingeniería matematica
facebook: cigmaoe
calendar: /curso_python_20181.ics
mailinglist: mailto:cigma-oe@eafit.edu.co
gravatar_url:
disqus_username:
